### ISSUE TITLE
Creates a lot of folders on mac

### ISSUE THREAD

**Issue by nathraQ** [manekinekko/angular2-dependencies-graph#5] opened 2016-04-13 22:05 UTC
Running ```ng2-dg --file bootstrap.ts``` with any project (tried it e.g. with AngularShowcase/angular2-sample-app) creates empty folders named a,b,c and so on.  

I'm using it with osx version 10.11.3  and node version v5.6.0

**Comment by manekinekko** [comment] 2016-04-14 20:40
@nathraQ that's weird. Because I just tested with `AngularShowcase/angular2-sample-app` and got the graph (see below). Can you give more details about how to reproduce your issue?

![image](https://cloud.githubusercontent.com/assets/1699357/14542892/b6fee46c-0291-11e6-906e-0e99c852e081.png)


![image](https://cloud.githubusercontent.com/assets/1699357/14542880/a0a6d9a4-0291-11e6-8724-b4535474d183.png)

**Comment by manekinekko** [comment] 2016-04-16 16:59
@nathraQ any updates ?

**Comment by bitsmag** [comment] 2016-04-18 20:35
I got another laptop today and didn't install the package globally - I got the same problem. 

The code which creates the directory uses process.cwd() which returns the current working directory. If the package is not installed globally you have to use "node node_modules/angular2-dependencies-graph/bin" to run the tool - the working directory is then the directory of the angular project, not the directory of the ng2-dg project. Using `__dirname` [solves the problem](http://stackoverflow.com/questions/9874382/whats-the-difference-between-process-cwd-vs-dirname)

I created a [pull request](https://github.com/manekinekko/angular2-dependencies-graph/pull/9). I didn't understand why there is a forEach loop to create the directory, thats why I removed the loop in the second commit.

**Comment by manekinekko** [comment] 2016-04-18 21:10
thanks @bitsmag I'll check your PR this WE.

**Comment by manekinekko** [comment] 2016-04-22 21:19
fix merged in https://github.com/manekinekko/angular2-dependencies-graph/pull/10

**Closed by manekinekko** 2016-04-22 21:19 UTC
Labels: bug
